#!/bin/bash

# create env.py automatically
# will have SESSION_COOKIE_NAME = "blockchain_"+random_string
# will have SECRET_KEY = random_string

echo "Creating env.py"
echo "SESSION_COOKIE_NAME = \"blockchain_$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)\"" > /usr/lib/python/eth_sandbox/env.py
echo "SECRET_KEY = \"$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)\"" >> /usr/lib/python/eth_sandbox/env.py

(
    cd /home/ctf/
    PYTHONUNBUFFERED=true gunicorn \
        --user ctf \
        --group ctf \
        --bind 0.0.0.0:$LAUNCHER_PORT \
        --daemon \
        --workers 4 \
        --threads 8 \
        --access-logfile /var/log/ctf/proxy.access.log \
        --error-logfile /var/log/ctf/proxy.error.log \
        --capture-output \
        --log-level debug \
        chal:app
)
