#!/bin/bash

PYTHONUNBUFFERED=true gunicorn \
    --user ctf \
    --group ctf \
    --bind 0.0.0.0:$PROXY_PORT \
    --daemon \
    --workers 16 \
    --threads 32 \
    --access-logfile /var/log/ctf/proxy.access.log \
    --error-logfile /var/log/ctf/proxy.error.log \
    --capture-output \
    --log-level debug \
    eth_sandbox.proxy:app
